name: Test and build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        working-directory: src
        run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        working-directory: src
        run: go build -o ../dist/terraform-provider-nginx .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/terraform-provider-nginx
